
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signscribe-app
  labels:
    app: signscribe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: signscribe
  template:
    metadata:
      labels:
        app: signscribe
    spec:
      containers:
      - name: signscribe
        image: signscribe:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: signscribe-service
spec:
  selector:
    app: signscribe
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signscribe-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: signscribe.example.com  # Replace with your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: signscribe-service
            port:
              number: 80
  tls:
  - hosts:
    - signscribe.example.com  # Replace with your actual domain
    secretName: signscribe-tls
